-- =====================================
-- DATAFLOW - E-COMMERCE SQL ANALYTICS
-- =====================================


-- =====================================
-- 1. TOTAL REVENUE
-- Calculates the total revenue generated
-- from all valid orders.
-- =====================================

SELECT
    SUM(total_amount) AS total_revenue
FROM orders;


-- =====================================
-- 2. TOTAL NUMBER OF ORDERS
-- Counts the total number of valid orders
-- present in the orders table.
-- =====================================

SELECT
    COUNT(*) AS total_orders
FROM orders;


-- =====================================
-- 3. AVERAGE ORDER VALUE
-- Calculates the average revenue generated
-- per order.
-- =====================================

SELECT
    AVG(total_amount) AS average_order_value
FROM orders;


-- =====================================
-- 4. REVENUE BY PRODUCT CATEGORY
-- Joins orders with products and calculates
-- total revenue generated by each category.
-- =====================================

SELECT
    p.category,
    SUM(o.total_amount) AS revenue
FROM orders o
JOIN products p
    ON o.product_id = p.product_id
GROUP BY p.category
ORDER BY revenue DESC;


-- =====================================
-- 5. TOP 10 PRODUCTS BY REVENUE
-- Calculates units sold and total revenue
-- for each product and returns the top 10.
-- =====================================

SELECT
    p.product_name,
    SUM(o.quantity) AS units_sold,
    SUM(o.total_amount) AS revenue
FROM orders o
JOIN products p
    ON o.product_id = p.product_id
GROUP BY
    p.product_id,
    p.product_name
ORDER BY revenue DESC
LIMIT 10;


-- =====================================
-- 6. REVENUE BY CITY
-- Joins orders with customers and calculates
-- total revenue generated from each city.
-- =====================================

SELECT
    c.city,
    SUM(o.total_amount) AS revenue
FROM orders o
JOIN customers c
    ON o.customer_id = c.customer_id
GROUP BY c.city
ORDER BY revenue DESC;


-- =====================================
-- 7. MONTHLY REVENUE
-- Groups orders by month and calculates
-- total revenue for each month.
-- =====================================

SELECT
    DATE_TRUNC(
        'month',
        order_date
    ) AS month,
    SUM(total_amount) AS revenue
FROM orders
GROUP BY month
ORDER BY month;


-- =====================================
-- 8. TOP 10 CUSTOMERS BY SPENDING
-- Calculates total spending for each customer
-- and returns the 10 highest-spending customers.
-- =====================================

SELECT
    c.customer_id,
    c.name,
    SUM(o.total_amount) AS total_spent
FROM orders o
JOIN customers c
    ON o.customer_id = c.customer_id
GROUP BY
    c.customer_id,
    c.name
ORDER BY total_spent DESC
LIMIT 10;


-- =====================================
-- 9. CUSTOMER RANKING USING RANK()
-- Uses a SQL window function to rank customers
-- based on their total spending.
-- =====================================

SELECT
    c.customer_id,
    c.name,
    SUM(o.total_amount) AS total_spent,

    RANK() OVER (
        ORDER BY SUM(o.total_amount) DESC
    ) AS customer_rank

FROM orders o

JOIN customers c
    ON o.customer_id = c.customer_id

GROUP BY
    c.customer_id,
    c.name;


-- =====================================
-- 10. PREVIOUS DAY REVENUE USING LAG()
-- First calculates daily revenue and then uses
-- LAG() to retrieve the previous day's revenue.
-- =====================================

WITH daily_sales AS (

    SELECT
        order_date,
        SUM(total_amount) AS revenue

    FROM orders

    GROUP BY order_date
)

SELECT
    order_date,
    revenue,

    LAG(revenue) OVER (
        ORDER BY order_date
    ) AS previous_day_revenue

FROM daily_sales

ORDER BY order_date;


-- =====================================
-- 11. CUMULATIVE REVENUE
-- Calculates daily revenue and then uses a
-- window function to calculate running revenue
-- over time.
-- =====================================

WITH daily_sales AS (

    SELECT
        order_date,
        SUM(total_amount) AS daily_revenue

    FROM orders

    GROUP BY order_date
)

SELECT
    order_date,
    daily_revenue,

    SUM(daily_revenue) OVER (
        ORDER BY order_date
    ) AS cumulative_revenue

FROM daily_sales

ORDER BY order_date;


-- =====================================
-- 12. CUSTOMERS SPENDING ABOVE AVERAGE
-- Uses a subquery to calculate each customer's
-- total spending and compares it with the
-- average spending across all customers.
-- =====================================

SELECT
    customer_id,
    total_spent

FROM (

    SELECT
        customer_id,
        SUM(total_amount) AS total_spent

    FROM orders

    GROUP BY customer_id

) customer_sales

WHERE total_spent > (

    SELECT AVG(total_spent)

    FROM (

        SELECT
            customer_id,
            SUM(total_amount) AS total_spent

        FROM orders

        GROUP BY customer_id

    ) avg_sales

)

ORDER BY total_spent DESC;